### PR TITLE
SIMSBIOHUB-541: Release Fixes - Update migrations to account for test/prod data

### PR DESCRIPTION
**Pull request by NickPhura**
## Links to Jira Tickets

n/a

## Description of Changes

Merge/update 2 migrations to fix an issue with the migration failing in test due to null data in a non-null column.

Unrelated to the above: bumped the openshift cpu/memory limits, mostly for test and prod, as they were fairly low despite having lots available.

## Testing Notes

I tested this locally by removing the latest 7 migrations, building/seeding my database with some records in the study_species and survey_observation tables, and then added back/ran the 7 migrations, and everything migrated as expected.

### CODE REVIEW

**Review by curtisupshall — DISMISSED** [review]
LGTM

**Review by al-rosenthal — APPROVED** [review]
🦫

**Review by KjartanE — APPROVED** [review]
🐈

**Review by curtisupshall — APPROVED** [review]
Tested locally, works great.

**Pull request merged**
