### PR TITLE
SIMSBIOHUB-621: Handle Bad Deployment Data

### PR DESCRIPTION
**Pull request by NickPhura**
## Links to Jira Tickets

https://apps.nrs.gov.bc.ca/int/jira/browse/SIMSBIOHUB-621

## Description of Changes

Initial support for bad data (warning) response from deployments endpoints.

## Testing Notes

If a survey has one or more deployments, and one or more of them reference a BCTW deployment ID that does not exist, the Manage Telemetry page should load successfully, showing a card in the left nav for each bad deployment record.

### CODE REVIEW

**Comment by mauberti-bc** [comment]
* Missing key prop on the bad deployments list item
* When a deployment with telemetry data is deleted, the telemetry UI table does not properly refresh; the rows remain but the deployment ID value of the rows gets removed

**Review by MacDeluca — DISMISSED** [review]
👍🏼

**Review by MacDeluca — DISMISSED** [review]
🦺

**Review by MacDeluca — APPROVED** [review]
🌡️

**Pull request merged**
