### PR TITLE
Tech debt: create the database procedures folder

### PR DESCRIPTION
**Pull request by curtisupshall**
## Description of Changes

- Moves the PGSQL stored procedures from migrations to a dedicated seed folder.
- Updates the database README file
- Removes unused Dockerfiles

## Testing Notes
You should be able to 
 - [ ] Delete a survey
 - [ ] Delete a project

### CODE REVIEW

**Review by al-rosenthal — COMMENTED** [review]
Testing this locally and I noticed a few things: 
- Running a clean web the project with multiple seeds fails to delete, likely and issue with the seed data not the delete 
- I created a new project -> survey _sampling site with blocks and stratums and the delete actions fails `survey_block_id` is still referenced `survey_sample_block`

**Review by al-rosenthal — DISMISSED** [review]
ran this locally and it looks good! 🍦

**Review by NickPhura — DISMISSED** [review]
🗡️

**Review by NickPhura — APPROVED** [review]

**Review by al-rosenthal — APPROVED** [review]
🧥 🗡️

**Pull request merged**
