### PR TITLE
SIMSBIOHUB 343 - Incorrect date overlap error in sampling methods

### PR DESCRIPTION
**Pull request by GrahamS-Quartech**
## Links to Jira Tickets

- [SIMSBIOHUB-343](https://apps.nrs.gov.bc.ca/int/jira/browse/SIMSBIOHUB-343)

## Description of Changes

- Fixed an issue where the yup schema used for editing sampling methods used the wrong field for a date overlap check. 
- Removed an unintended required(). 
- Added a refresh call when submitting sampling method changes so they are reflected in the UI. Otherwise you will still see the previous value if you go back to the sampling methods view even though the new value did save to the db.

### CODE REVIEW

**Review by curtisupshall — APPROVED** [review]

**Comment by JeremyQuartech** [comment]
How can I test these changes? Should this be branched from dev, or dev-staging?

**Comment by curtisupshall** [comment]
> How can I test these changes? Should this be branched from dev, or dev-staging?

PR needs to rebuild since the base branch changed from `dev` to `dev-staging`. Otherwise, it should be testable in Openshift

**Comment by curtisupshall** [comment]
See: https://github.com/bcgov/biohubbc/pull/1145

**Review by al-rosenthal — APPROVED** [review]
looks good

**Review by curtisupshall — APPROVED** [review]
Manually tested. Appears to be working as intended 👍

**Pull request merged**
