### PR TITLE
SIMSBIOHUB-491: Remove code for project drafts

### PR DESCRIPTION
**Pull request by curtisupshall**
## Overview
Because the project form is no longer comprehensive enough to justify project drafts, we want to remove project drafts from SIMS.

## Links to Jira Tickets

- https://apps.nrs.gov.bc.ca/int/jira/browse/SIMSBIOHUB-491

## Description of Changes

- Removes all code associated with creating, viewing, and editing project drafts.

## Testing Notes
- You should still be able to:
  - [ ] Create a project
  - [ ] Edit a project
  - [ ] View a project

### CODE REVIEW

**Review by KjartanE — DISMISSED** [review]
Tested locally, works as intended. 👍

**Review by al-rosenthal — DISMISSED** [review]
ran this locally and it works 📽️

**Review by KjartanE — APPROVED** [review]
🐈

**Review by al-rosenthal — APPROVED** [review]
⛵

**Pull request merged**
