### PR TITLE
Error message that users can have duplicate entries on IUCN, species and permits

### PR DESCRIPTION
**Pull request by sdevalapurkar**
# Overview

## This PR contains the following changes

- Error message that users can have duplicate entries on IUCN, species and permits
- bunch of missing tests added
- https://quartech.atlassian.net/browse/BHBC-956

## This PR contains the following types of changes

- [x] Enhancement (improvements to existing functionality)
- [x] Bug fix (change which fixes an issue)

## How Has This Been Tested?

- Locally

## Screenshots

Screenshot 2021-04-01 143146
Screenshot 2021-04-01 143249

### CODE REVIEW

**Review by anissa-agahchen — COMMENTED** [review]
I ran it locally, and it works fine for iucn and permits.  Did you intend to include species in here?  otherwise adjust the title of the PR and do the species in a different PR?

**Comment by sdevalapurkar** [comment]
> I ran it locally, and it works fine for iucn and permits. Did you intend to include species in here? otherwise adjust the title of the PR and do the species in a different PR?

Done, species validation is handled too :)

**Review by NickPhura — APPROVED** [review]

**Comment by NickPhura** [comment]
Do we need to add a test for "renders with errors" for species? Just noticed that test exists for the permit/iucn, but is maybe missing for species?

**Comment by sdevalapurkar** [comment]
> Do we need to add a test for "renders with errors" for species? Just noticed that test exists for the permit/iucn, but is maybe missing for species?

The projectspeciesform is at 100% coverage - cause the error is purely based on validation and when you press next - so technically I think that may need to exist in the create project page tests? I think it is fine for this PR

**Comment by anissa-agahchen** [comment]
I found a bug
Screen Shot 2021-04-07 at 9 34 38 AM

**Pull request merged**
