### PR TITLE
Bug Fix: Misc

### PR DESCRIPTION
**Pull request by NickPhura**
## Links to Jira Tickets

n/a

## Description of Changes

Fix geojson zod schema usage (my fault from previous PR)
- Was causing the survey page to fail to load.
Update platform publish classes to match latest version expected by BioHub.

## Testing Notes

- Survey related pages load correctly once again.
- Publish works (pending matching changes on the BioHub side which have not yet been merged to the feature branch)

### CODE REVIEW

**Review by al-rosenthal — DISMISSED** [review]
ran this locally and it looks good 🛠️

**Review by al-rosenthal — DISMISSED** [review]
🙈

**Review by curtisupshall — APPROVED** [review]
Code looks good to me 📦

**Review by al-rosenthal — APPROVED** [review]
🏂

**Pull request merged**
