### PR TITLE
BHBC-794: Species section, multiselect widget + tests

### PR DESCRIPTION
**Pull request by NickPhura**
# Overview

## Links to jira tickets

https://quartech.atlassian.net/browse/BHBC-794

## This PR contains the following changes

- Add multi-select autocomplete field
- Add species section
  - Update project endpoint to also save species info
  - Add migration to update db models to add species tables
- Add some hardcoded species values to temporarily satisfy the species dropdowns
  - These particular values are just a concatenation of some species names/latin names from the CDC public search for non-critical species, so definitely a complete or final version.
  - This will need to be flushed out further, before release, once we get a better handle on the whole taxon topic

## This PR contains the following types of changes

- [x] New feature (change which adds functionality)
- [ ] Enhancement (improvements to existing functionality)
- [ ] Bug fix (change which fixes an issue)
- [ ] Misc cleanup / Refactoring / Documentation
- [ ] Version change

## Checklist

A list of items that are good to consider when making any changes.

_Note: this list is not exhaustive, and not all items are always applicable._

### General

- [x] I have performed a self-review of my own code

### Code

- [ ] New files/classes/functions have appropriately descriptive names and comment blocks to describe their use/behaviour
- [ ] I have avoided duplicating code when possible, moving re-usable pieces into functions
- [ ] I have avoided hard-coding values where possible and moved any re-usable constants to a constants file
- [ ] My code is as flat as possible (avoids deeply nested if/else blocks, promise chains, etc)
- [ ] My code changes account for null/undefined values and handle errors appropriately
- [ ] My code uses types/interfaces to help describe values/parameters/etc, help ensure type safety, and improve readability

### Style

- [ ] My code follows the established style conventions
- [x] My code uses native material-ui components/icons/conventions when possible

### Documentation

- [ ] I have commented my code sufficiently, such that an unfamiliar developer could understand my code
- [ ] I have added/updated README's and related documentation, as needed

### Tests

- [x] I have added/updated unit tests for any code I've added/updated
- [x] I have added/updated the Postman requests/tests to account for any API endpoints I've added/updated

### Linting/Formatting

- [x] I have run the linter and fixed any issues, as needed  
       _See the `lint` commands in package.json_
- [x] I have run the formatter and fixed any issues, as needed  
       _See the `format` commands in package.json_

### SonarCloud

- [x] I have addressed all SonarCloud Bugs, Vulnerabilities, Security Hotspots, and Code Smells

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Screenshots

Please add any relevant UI screenshots, if applicable.

### CODE REVIEW

**Comment by NickPhura** [comment]
@rstens Most of the duplication is coming from the unit tests.  Can we disable test files from being checked for duplicate code?  I also rejected some smells it identified for empty arrow functions, etc, which are normal in the tests to stub out functions, etc.

Edit: I took a whack at updating the `.sonarcloud.properties` file, which is included in this PR.  Looks like its working as desired.

**Review by anissa-agahchen — CHANGES_REQUESTED** [review]
It looks good overall.  The main issue I found:
* when a species is selected in the focal species list, or the ancillary species list, it should not be available to select again

Less important, but worth noting:
* the postman file to be reverted completely, I think.... I couldn't find any intentional changes in that file.

**Review by rstens — COMMENTED** [review]
Do we have a standard list of API HTTP return codes that we adhere to?

Also: Just to be clear: we are not using knex as a query builder?

**Comment by rstens** [comment]
> @rstens Most of the duplication is coming from the unit tests. Can we disable test files from being checked for duplicate code? I also rejected some smells it identified for empty arrow functions, etc, which are normal in the tests to stub out functions, etc.
> 
> Edit: I took a whack at updating the `.sonarcloud.properties` file, which is included in this PR. Looks like its working as desired.

Should be fine.

**Comment by NickPhura** [comment]
@anissa-agahchen 
> 
> 
> It looks good overall. The main issue I found:
> 
>     * when a species is selected in the focal species list, or the ancillary species list, it should not be available to select again
> 

In the interest of progress I think this will have to remain as it is for now.  There isn't a good solution to account for this that wont also take a bunch of work.  If it becomes an issue later we can see what can be done to update it.

> 
> Less important, but worth noting:
> 
>     * the postman file to be reverted completely, I think.... I couldn't find any intentional changes in that file.

There were no brand new endpoints, but I did update the `POST project` endpoint.  I added the new coordinator and species fields to the json object.

**Comment by NickPhura** [comment]
@rstens 
> 
> 
> Do we have a standard list of API HTTP return codes that we adhere to?

Mostly yes.  

In the root openapi spec, there are a number of common responses listed, which are mostly for error cases (401, 403, 409, 500, 503, etc).  These are then referenced as possible responses in each of the endpoint openapi specs, alongside the 200 happy path response.  Right now, I just tend to list all of them, even if I only intentionally throw a few.  Something to refine later on.

That being said, there is no response validation currently, so there is nothing stopping us from throwing a code that isn't in the list of responses.  There is some response validation I believe that can be leveraged, but I haven't investigated how it works yet..

(One thing I want to do at some point, is make some util functions for throwing errors, so we have some pre-made documented `throw500('some message', error)` type calls that can be made without having to think about it.)

>
> 
> Also: Just to be clear: we are not using knex as a query builder?

We have not been using it, correct.  Charlie is leveraging the fancy psql modelling tool that Quartech bought a license for.  
And then we have either been running those sql files directly, by dropping them unchanged into the knex raw template string, or in the case of smaller one-off changes, just copying the sql contents directly into the knex raw template string.

**Review by anissa-agahchen — APPROVED** [review]
I'll throw a ticket in the backlog, about the species, and we can deal with it when/if there is a need

**Pull request merged**
