### PR TITLE
Implement Objectives section in Project View Page

### PR DESCRIPTION
**Pull request by sdevalapurkar**
<details open>
  <summary><a href="https://quartech.atlassian.net/browse/BHBC-871" title="BHBC-871" target="_blank">BHBC-871</a></summary>
  <br />
  <table>
    <tr>
      <th>Summary</th>
      <td>Implement Objectives section in Project View Page </td>
    </tr>
    <tr>
      <th>Type</th>
      <td>
        Story
        Story
      </td>
    </tr>
    <tr>
      <th>Status</th>
      <td>In Progress</td>
    </tr>
    <tr>
      <th>Points</th>
      <td>N/A</td>
    </tr>
    <tr>
      <th>Labels</th>
      <td>-</td>
    </tr>
  </table>
</details>

---

# Overview

## Links to jira tickets

- https://quartech.atlassian.net/browse/BHBC-871

## This PR contains the following changes

- Truncate length of objectives to 850 characters (or closest period) and show it with ability to expand and read more/read less as required

## This PR contains the following types of changes

- [x] New feature (change which adds functionality)
- [x] Enhancement (improvements to existing functionality)

## How Has This Been Tested?

- Locally

## Screenshots

Screenshot 2021-03-15 122202
Screenshot 2021-03-15 122225

### CODE REVIEW

**Comment by anissa-agahchen** [comment]
The objectives field in the DB has a max of length 3000.  Can you put in a check that the objectives are not longer than 3000 characters?

[2021-03-15 20:24:39] (error) (app): errorMiddleware - unexpected error
error: value too long for type character varying(3000)

**Comment by anissa-agahchen** [comment]
can you make a couple of changes on the view page so that the paragraphs are not all merged?  
Screen Shot 2021-03-15 at 12 28 34 PM

**Comment by anissa-agahchen** [comment]
Can you make the objectives section in the View page display multiple paragraphs separately?  Right now, they all merge.  The attached snapshot should show 2 paragraphs
Screen Shot 2021-03-15 at 1 57 17 PM

**Comment by NickPhura** [comment]
> 
> 
> Can you make the objectives section in the View page display multiple paragraphs separately? Right now, they all merge. The attached snapshot should show 2 paragraphs
> Screen Shot 2021-03-15 at 1 57 17 PM

This would require changes to the create project controls as well, as we would need to render a rich text control (or something similar) that accounts for the new lines as actual characters that get stored in the database. And then similarly on the view page, render it as rich text so that the new line characters turn into new lines, and don't just get printed to the page.

They may desire this in the end, but for now during this first pass we can probably not worry about it.

This would also be something that could come from user testing: maybe no one ever types more than 1 paragraph, or maybe they all type a ton and the separation of paragraphs is important.

**Comment by sdevalapurkar** [comment]
got the multi paragraph view working !!
Screenshot 2021-03-15 142746

**Comment by anissa-agahchen** [comment]
Really close!  

nit: Your paragraph break is recognized correctly in the DB, but on the view page, you need to give it a bit of space.

**Review by NickPhura — APPROVED** [review]

**Pull request merged**
