### PR TITLE
SIMSBIOHUB-129: Upgrade to MUI V5

### PR DESCRIPTION
**Pull request by curtisupshall**
# Overview

We are currently using MUI version 4, which is now outdated. This PR updates MUI to version 5, similar to [the update performed last year in BioHub.](https://github.com/bcgov/biohubbc-platform/commit/177dcf9f655891505ab69f6bf06916e0f3e590d9)

## Links to Jira tickets

 - https://apps.nrs.gov.bc.ca/int/jira/browse/SIMSBIOHUB-129

## Description of relevant changes

 - Update MUI to version 5, including updates to component imports and theming

### CODE REVIEW

**Review by al-rosenthal — DISMISSED** [review]
🕶️

**Comment by KjartanE** [comment]
:cat

**Review by KjartanE — DISMISSED** [review]
o7

**Review by al-rosenthal — DISMISSED** [review]
🍦

**Review by al-rosenthal — APPROVED** [review]
🍦

**Review by NickPhura — APPROVED** [review]
🐛

**Pull request merged**
