### PR TITLE
SIMSBIOHUB-354-355: Study area and Sampling sites on observations map

### PR DESCRIPTION
**Pull request by al-rosenthal**
## Links to Jira Tickets

[SIMSBIOHUB-354](https://apps.nrs.gov.bc.ca/int/jira/browse/SIMSBIOHUB-354)
[SIMSBIOHUB-355](https://apps.nrs.gov.bc.ca/int/jira/browse/SIMSBIOHUB-355)

## Description of Changes

- Added sampling site locations to the observation map
- Added study area locations to the observation map

## Testing Notes

- Create/ Edit a survey
- Add a sampling site 
- Navigate to survey details page and see features on the map
- Toggle layers with map control in the bottom right of the map

### CODE REVIEW

**Comment by al-rosenthal** [comment]
Noticed a few things testing this:
- A strange UI issue with the controls at the top of the table. The buttons are mismatched sizes and there is a strange bar cutting through the time column if scrolling to the right of the table
Screenshot 2023-11-01 144235


- When deleting a record the observations count at the top of the table
- Ran into an issue deleting records
  -  Import records
  - Edit any record
  - Delete the same record
  - Save changes
- Not an error but it is a strange interaction to create a new record and try and delete that record before saving any changes. The UI throws an error but I think it should just remove the record

**Review by NickPhura — APPROVED** [review]

**Comment by GrahamS-Quartech** [comment]
Tested this on the deployed pod. Seems to work as expected.
Perhaps outside the scope of this ticket, but I think it would be good if there was some way to see a label of which feature is which when clicking on one. It's not really clear which is a study area and which is a sampling site since everything is blue and they can overlap. Similarly, might be nice if you could toggle on/off individual elements rather than all sampling sites and all study areas.

**Review by GrahamS-Quartech — APPROVED** [review]

**Comment by al-rosenthal** [comment]
> Tested this on the deployed pod. Seems to work as expected. Perhaps outside the scope of this ticket, but I think it would be good if there was some way to see a label of which feature is which when clicking on one. It's not really clear which is a study area and which is a sampling site since everything is blue and they can overlap. Similarly, might be nice if you could toggle on/off individual elements rather than all sampling sites and all study areas.

I think we'll be keeping this pretty simple for now and make this interaction a little more complex as we get a better idea of how users want to interact with the map. I did add an on over for the study areas and sample sites so hopefully it is a little less confusing which is which when toggling. The observations are also now an orange color so they stand out a bit more

**Comment by GrahamS-Quartech** [comment]
> I think we'll be keeping this pretty simple for now and make this interaction a little more complex as we get a better idea of how users want to interact with the map. I did add an on over for the study areas and sample sites so hopefully it is a little less confusing which is which when toggling. The observations are also now an orange color so they stand out a bit more

Tested this again locally. I think the onOver and color changes are good, definitely sufficient for now.

One thing I noticed: It seems that when you refresh the page, the sample site can load in after the study area, so the map bounds will not be fit to both shapes.

**Review by curtisupshall — APPROVED** [review]
Code looks good

**Review by NickPhura — APPROVED** [review]

**Pull request merged**
