### PR TITLE
Tech debt: Fixed linting errors and skipped tests

### PR DESCRIPTION
**Pull request by curtisupshall**
Fixes frontend linting errors and skipped tests.

### CODE REVIEW

**Review by al-rosenthal — DISMISSED** [review]
🍡

**Comment by NickPhura** [comment]
@curtisupshall 

Found an issue: If you edit the map, and select a layer from the dropdown (nrm regional boundaries in my case), you get an infinite loop of requests to the openmaps service. I confirmed this is not the case in Dev. It looks like `throttledGetFeatures` is getting called in a loop.

**Review by al-rosenthal — DISMISSED** [review]
ran this locally and it works as expected
🐇

**Comment by NickPhura** [comment]
@curtisupshall Maps seem happier after the latest changes from what I can tell.

There is still 1 dependency error popping up though, in ProjectAdvancedFilters.tsx L91.

I did give it a try locally, and adding the dependency (biohubApi.taxonomy) it is complaining about seems to work just fine (doesn't trigger any loops or anything).

**Review by NickPhura — APPROVED** [review]

**Review by KjartanE — APPROVED** [review]
🐈

**Review by al-rosenthal — APPROVED** [review]
🗺️

**Pull request merged**
