### PR TITLE
fixed survey proprietor issue

### PR DESCRIPTION
**Pull request by anissa-agahchen**
Fixing the survey proprietor problem

### CODE REVIEW

**Review by sdevalapurkar — COMMENTED** [review]
remove console logs

**Comment by sdevalapurkar** [comment]
formatting checks need to be fixed

**Review by sdevalapurkar — COMMENTED** [review]
this file should have no changes
`api/src/paths/project/{projectId}/survey/{surveyId}/update.ts`

**Comment by anissa-agahchen** [comment]
@sdevalapurkar I addressed the formatting issues, but left a space in update.ts conditions as I find it more readable that way.

**Review by sdevalapurkar — APPROVED** [review]

**Pull request merged**
