### PR TITLE
SIMSBIOHUB-487: Collaborators and Coordinators Auth Guard

### PR DESCRIPTION
**Pull request by KjartanE**
## Links to Jira Tickets

- https://apps.nrs.gov.bc.ca/int/jira/browse/SIMSBIOHUB-487

## Description of Changes

- Roll guard the following functionality on the Survey Page:
   - [ ] Survey Edit
   - [ ] Manage Observations and Telemetry 
   - [ ] Manage Marked and Known Animals
   - [ ] Marked and Known Animals Context Menu for each record 
   - [ ] Document Upload 
   - [ ] Context Menu for Documents (guard delete functionality)
   - [ ] Survey Details Component

- Prevent access to following pages (403 error)
   - [ ] Manage Observations 
   - [ ] Manage Telemetry 
   - [ ] Manage Animals
   - [ ] Create Survey
   - [ ] Edit Survey

- Roll guard the following functionality on the Project Page
   - [ ] Settings
   - [ ] Create Survey
   - [ ] Upload Documents
   - [ ] Context Menu for Documents (guard delete functionality)

- Prevent access to the following pages (403 error)
   - [ ] Edit Project
   - [ ] Manage Project Team

- Roll guard the following functionality on the Project List Page
   - [ ] Create Project

- Prevent access the following pages (403 error)
   - [ ] Create Project Page

## Testing Notes
- Test all referenced pages and components for individual authentication levels
   - [ ] system admin - can do everything
   - [ ] data admin - can do everything except manage system users
   - [ ] project coordinator - can do everything under a project
   - [ ] project collaborator - can do everything under a project except manage project users, delete a project/survey, publish a survey
   - [ ] project observer - can do nothing

### CODE REVIEW

**Review by al-rosenthal — COMMENTED** [review]
I tried testing this out as an full admin and I tried to create a project but was met with a state error around the codes context provider.

**Comment by KjartanE** [comment]
> I tried testing this out as an full admin and I tried to create a project but was met with a state error around the codes context provider.

Seemed to be a merged issue, resolved the bug.

**Review by NickPhura — DISMISSED** [review]
🔒

**Review by al-rosenthal — APPROVED** [review]
🥡

**Review by NickPhura — APPROVED** [review]

**Pull request merged**
