### PR TITLE
Application Header and Footer Updates

### PR DESCRIPTION
**Pull request by jeznorth**
## Links to Jira Tickets

- Support updated layout of application required in SIMSBIOHUB-219

## Description of Changes

- Implemented full-width header and footer components
- Collapsed the navbar into a single contained element
- Added responsive menu to support smaller viewports
- Removed global styling from externally referenced stylesheet to application theme file.

## Testing Notes

- {List any relevant testing considerations, necessary pre-reqs, and areas of the app to focus on. Specifically, include anything that will help the reviewers of this PR verify the code is functioning as expected.}

### CODE REVIEW

**Review by curtisupshall — DISMISSED** [review]
Test manually. New header is looking great! 💅

**Review by al-rosenthal — DISMISSED** [review]
🏞️

**Review by curtisupshall — DISMISSED** [review]

**Comment by NickPhura** [comment]
@jeznorth 
Minor: Shouldn't the "Support" header item always be at the far right of the list of menu items (and just before the "Log Out" option in the collapsed menu)? Currently, for non-admins it is. But for admin users its between "Projects" and "Manage Users", which feels a bit funny.

Discussed: will address separately afterwards

**Review by NickPhura — APPROVED** [review]

**Review by al-rosenthal — APPROVED** [review]
🤖

**Pull request merged**
