### PR TITLE
See Status of File Upload When Uploading Map Files (e.g. GPX / KML / Shapefile)

### PR DESCRIPTION
**Pull request by sdevalapurkar**
# Overview

## Links to jira tickets

- https://quartech.atlassian.net/browse/BHBC-1425

## This PR contains the following changes

- See Status of File Upload When Uploading Map Files (e.g. GPX / KML / Shapefile)

## This PR contains the following types of changes

- [x] Enhancement (improvements to existing functionality)

### CODE REVIEW

**Comment by sdevalapurkar** [comment]
@rstens this change will break cypress tests - they'll need to be updated to address the change

**Review by anissa-agahchen — DISMISSED** [review]
Looks good!

**Review by rstens — COMMENTED** [review]
Please: you have to give it a [data-testid="boundary-file-upload"] otherwise it is tricky for me to automate. I'll add to update to the test file then to this PR.

BTW, why is our coverage down the drain? @sdevalapurkar

**Comment by sdevalapurkar** [comment]
> Please: you have to give it a [data-testid="boundary-file-upload"] otherwise it is tricky for me to automate. I'll add to update to the test file then to this PR.
> 
> BTW, why is our coverage down the drain? @sdevalapurkar

by down the drain do you mean down by 0.3%?

**Comment by sdevalapurkar** [comment]
> Please: you have to give it a [data-testid="boundary-file-upload"] otherwise it is tricky for me to automate. I'll add to update to the test file then to this PR.
> 
> BTW, why is our coverage down the drain? @sdevalapurkar

ok coverage should be good now 😉

**Review by rstens — APPROVED** [review]

**Review by anissa-agahchen — APPROVED** [review]

**Pull request merged**
