### PR TITLE
SIMSBIOHUB-32-2: Additional Tweaks to lint/format versions, import paths, tsconfig, etc.

### PR DESCRIPTION
**Pull request by NickPhura**
# Overview

## Links to Jira tickets

- {List all applicable Jira tickets}

## Description of relevant changes

- Update eslint/prettier/jest versions
  - Was getting some odd issues, this seemed to fix them.
- Update tsconfig: 'react' -> 'react-jsx'
  - Remove unused React imports (which are now global when using 'react-jsx'
- Update some material-ui import paths

## PR Checklist

A list of items that are good to consider when making any changes.

_Note: this list is not exhaustive, and not all items are always applicable._

### Code

- [ ] New files/classes/functions have appropriately descriptive names and comment blocks to describe their use/behaviour
- [ ] I have avoided duplicating code when possible, moving re-usable pieces into functions
- [ ] I have avoided hard-coding values where possible and moved any re-usable constants to a constants file
- [ ] My code is as flat as possible (avoids deeply nested if/else blocks, promise chains, etc)
- [ ] My code changes account for null/undefined values and handle errors appropriately
- [ ] My code uses types/interfaces to help describe values/parameters/etc, help ensure type safety, and improve readability

### Style

- [ ] My code follows the established style conventions
- [ ] My code uses native material-ui components/icons/conventions when possible

### Documentation

- [ ] I have commented my code sufficiently, such that an unfamiliar developer could understand my code
- [ ] I have added/updated README's and related documentation, as needed

### Tests

- [ ] I have added/updated unit tests for any code I've added/updated
- [ ] I have added/updated the Postman requests/tests to account for any API endpoints I've added/updated

### Linting/Formatting

- [ ] I have run the linter and fixed any issues, as needed  
       _See the `lint` commands in package.json_
- [ ] I have run the formatter and fixed any issues, as needed  
       _See the `format` commands in package.json_

### SonarCloud

- [ ] I have addressed all SonarCloud Bugs, Vulnerabilities, Security Hotspots, and Code Smells

### CODE REVIEW

**Comment by NickPhura** [comment]
I was getting some funny issues with the formatter and then jest, but version bumps seemed to fix them. But would definitely be best if someone could download and run it all locally to make sure its happy now (and I wasn't just getting some weird local issues).

**Comment by anissa-agahchen** [comment]
@NickPhura this message is coming up in the app log:

One of your dependencies, babel-preset-react-app, is importing the
"@babel/plugin-proposal-private-property-in-object" package without
declaring it in its dependencies. This is currently working because
"@babel/plugin-proposal-private-property-in-object" is already in your
node_modules folder for unrelated reasons, but it may break at any time.

babel-preset-react-app is part of the create-react-app project, which
is not maintianed anymore. It is thus unlikely that this bug will ever
be fixed. If you are starting a new project, you may consider using
maintained alternatives such as Vite (https://vitejs.dev/) instead.

Add "@babel/plugin-proposal-private-property-in-object" to your
devDependencies to work around this error. This will make this message
go away.

**Review by al-rosenthal — DISMISSED** [review]
Looked over the changes, things look good 🕶️

**Comment by NickPhura** [comment]
> 

Yeah I saw that. Its a bit of an odd message, Im pretty sure its one of those advertising messages, which is why its mentioning vite.

I was going to just look into a resolution for it separately, as its not a true warning.

**Review by curtisupshall — DISMISSED** [review]
🚀

**Comment by NickPhura** [comment]
Had to merge in latest dev, and there was a conflict in a package lock, so it reset reviews.

**Review by al-rosenthal — APPROVED** [review]
🐋

**Review by anissa-agahchen — APPROVED** [review]

**Pull request merged**
