### PR TITLE
SIMSBIOHUB-444, 456 - Shared Documents rename; No Deployments placeholder

### PR DESCRIPTION
**Pull request by curtisupshall**
## Links to Jira Tickets

 - https://apps.nrs.gov.bc.ca/int/jira/browse/SIMSBIOHUB-444
 - https://apps.nrs.gov.bc.ca/int/jira/browse/SIMSBIOHUB-456

## Description of Changes

 - SIMSBIOHUB-444: Renamed project Documents to 'Shared Files'.
 - SIMSBIOHUB-456: Shows empty state ("No Deployments") for deployments listed on telemetry page.
 - Minor UI tweaks

### CODE REVIEW

**Review by jeznorth — DISMISSED** [review]
Approved.

**Review by al-rosenthal — COMMENTED** [review]
Should the documents section of the survey page also be called 'Shared Files'?

**Review by NickPhura — APPROVED** [review]
LGTM (only did a static look over)

**Comment by curtisupshall** [comment]
> Should the documents section of the survey page also be called 'Shared Files'?

Negative. Just for Projects.

**Review by al-rosenthal — APPROVED** [review]
👾

**Pull request merged**
